
# Mama CLI Configuration File
# Generated at: 2025-01-15T01:44:06.885Z
# Author: Mataraman Dev & Wahyu A. Arifin
# Version: 1.0.1

# Project name
name: mama

# Project type (available options: next, next-fullstack, bun-hono, flutter)
type: next-fullstack

# Directory configurations
dir:
    # React/Next.js components directory
    components: src/components
    # Custom hooks directory
    hooks: src/hooks
