/**
 * @file Login.tsx
 * @author mama-cli
 * @generated at 2025-01-16T06:59:28.766Z
 * This file is generated by Mama CLI
 */

import React from 'react';

interface LoginProps { }

const LoginScreen: React.FC <LoginProps > = () => {
    return (
        <div>
            <h1>Screen Login!</h1>
        </div>
    );
};

export default LoginScreen;
