import type { Metadata } from "next";
import "@/styles/globals.css";
import { ENV } from "@/configs/environment";
import AppLayout from "@/interfaces/layouts/app.layout";
import { lilyScriptOne } from "@/styles/fonts/main";
import NextTopLoader from "nextjs-toploader";
import { ProviderReduxToolkit } from "@/providers/redux.provider";

export const metadata: Metadata = {
	title: "MAMA CLI",
	description: "Generated by mama cli",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${lilyScriptOne.className} antialiased`}>
				<NextTopLoader
					height={2}
					color={ENV.LOADER_COLOR}
					showSpinner={false}
				/>
				<ProviderReduxToolkit>
					<AppLayout>{children}</AppLayout>
				</ProviderReduxToolkit>
			</body>
		</html>
	);
}
