---
to: <%= directory %>/<%= name %>.tsx
---
/**
 * @file <%= name %>.tsx
 * 
 * This file is automatically generated by mama.
 * 
 * This is a basic React functional component in TypeScript.
 * The component is named <%= name %> and is placed in the directory: <%= directory %>.
 * 
 * You can modify this file to suit your needs.
 * 
 * Generated by Mama CLI. For more information, visit https://github.com/ItPohgero/mama-cli
 */

import React from 'react';

interface <%= name %>Props {}

const <%= name %>: React.FC<<%= name %>Props> = () => {
    return (
        <div>
            <h1>Hello from <%= name %> screen!</h1>
            <p>This file is placed in the directory: <%= directory %></p>
        </div>
    );
};

export default <%= name %>;
