/**
 * @author <%= author %>
 * @generated at <%= createdAt %>
 * This file is generated by Mama CLI
 */

import { ApiClient } from "@/server/clients/hono.client";
import type <%= name %>Schema from "@/server/schema/<%= _name %>.schema";
import { useMutation } from "@tanstack/react-query";
import type { z } from "zod";
import { type ErrorResponse, OnError } from "@/utils/asert_error";

const mutationFn = async (data: z.infer<typeof <%= name %>Schema>) => {
	try {
		const client = await ApiClient();
		const r = await client.api.ex.$post({
			json: data,
		});
		if (!r.ok) {
			const err: ErrorResponse = await r.json();
			const error = OnError(err);
			throw new Error(`Ups : ${error}`);
		}
		const resp = await r.json();
		return resp;
	} catch (error) {
		const er = error instanceof Error ? error.message : String(error);
		throw new Error(er);
	}
};

const Call<%= name %> = () => {
	return useMutation({
		mutationKey: ["<%= name %>"],
		mutationFn,
	});
};

export default Call<%= name %>;

