/**
 * @author <%= author %>
 * @generated at <%= createdAt %>
 * This file is generated by Mama CLI
 */

import type { Context } from "hono";

const <%= name %>Controller = async (c: Context) => {
    try {
        return c.json(
            {
                message: "Success",
                results: null
            },
            200,
        );
    } catch (error) {
        return c.json(
            {
                message: "Error",
                results: error,
            },
            500,
        );
    }
};

export default <%= name %>Controller;
