/**
 * @author <%= author %>
 * @generated at <%= createdAt %>
 * This file is generated by Mama CLI
 */

import { type FC, Fragment, type PropsWithChildren } from "react";

const <%= name %>Layout: FC<PropsWithChildren> = () => {
    return (
		<Fragment>
			<main>{children}</main>
		</Fragment>
	);
};

export default <%= name %>Layout;
