/**
 * @author <%= author %>
 * @generated at <%= createdAt %>
 * This file is generated by Mama CLI
 */

import { z } from "zod";
const <%= name %>Schema = z.object({
	example: z.string(),
});
export type <%= name %>Schema = z.infer<typeof <%= name %>Schema>;
export default <%= name %>Schema;
