/**
 * @file <%= name %>.tsx
 * @author <%= author %>
 * @generated at <%= createdAt %>
 * This file is generated by Mama CLI
 */

import React from 'react';

type <%= name %>Props = Record<string, never>


const <%= name %>Screen: React.FC <<%= name %>Props > = () => {
    return (
        <div>
            <h1>Screen <%= name %>!</h1>
        </div>
    );
};

export default <%= name %>Screen;
