/**
 * @file <%= name %>.tsx
 * @author <%= author %>
 * @generated at <%= createdAt %>
 * This file is generated by Mama CLI
 */

import React from 'react';

interface <%= name %>Props { }

const <%= name %>Screen: React.FC <<%= name %>Props > = () => {
    return (
        <div>
            <h1>Hello from <%= name %>!</h1>
        </div>
    );
};

export default <%= name %>Screen;
